employee/urls.py
from django.urls import path
from . import views


app_name = 'employee'
urlpatterns = [
    path('', views.employee_list, name='list'),
    path('<int:pk>/', views.employee_detail, name='detail'),
    path('add/', views.EmployeeCreateView.as_view(), name='add'),
    path('update/<int:pk>/', views.EmployeeUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.EmployeeDeleteView.as_view(), name='delete'),
    path('history/', views.employee_history_list, name='history'),
    
]

nguhub/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.user_login, name='signin'),
    path('logout/', views.user_logout, name='logout'),

    path('employee/', include('employee.urls', namespace='employee')),
    path('equipment/', include('equipment.urls', namespace='equipment')),

    # Довідники
     ##Location
    path('directory/location/', views.directory_location_list, name='directory_location_list'),
    path('directory/location/add/', views.LocationCreateView.as_view(), name='directory_location_add'),
    path('directory/location/update/<int:pk>/', views.LocationUpdateView.as_view(), name='directory_location_update'),
    path('directory/location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='directory_location_delete'),
     ##Placement
    path('directory/placement/', views.directory_placement_list, name='directory_placement_list'),
    path('directory/placement/add/', views.PlacementCreateView.as_view(), name='directory_placement_add'),
    path('directory/placement/update/<int:pk>/', views.PlacementUpdateView.as_view(), name='directory_placement_update'),
    path('directory/placement/delete/<int:pk>/', views.PlacementDeleteView.as_view(), name='directory_placement_delete'),
    ##ActionPost
    path('directory/actionpost/', views.directory_actionpost_list, name='directory_actionpost_list'),
    path('directory/actionpost/add/', views.ActionPostCreateView.as_view(), name='directory_actionpost_add'),
    path('directory/actionpost/update/<int:pk>/', views.ActionPostUpdateView.as_view(), name='directory_actionpost_update'),
    path('directory/actionpost/delete/<int:pk>/', views.ActionPostDeleteView.as_view(), name='directory_actionpost_delete'),
    ##EquipmentCategory
    path('directory/equipmentcategory/', views.directory_equipmentcategory_list, name='directory_equipmentcategory_list'),
    path('directory/equipmentcategory/add/', views.EquipmentCategoryCreateView.as_view(), name='directory_equipmentcategory_add'),
    path('directory/equipmentcategory/update/<int:pk>/', views.EquipmentCategoryUpdateView.as_view(), name='directory_equipmentcategory_update'),
    path('directory/equipmentcategory/delete/<int:pk>/', views.EquipmentCategoryDeleteView.as_view(), name='directory_equipmentcategory_delete'),
    ##EquipmentStatuses
    path('directory/equipmentstatus/', views.directory_equipmentstatus_list, name='directory_equipmentstatus_list'),
    path('directory/equipmentstatus/add/', views.EquipmentStatusCreateView.as_view(), name='directory_equipmentstatus_add'),
    path('directory/equipmentstatus/update/<int:pk>/', views.EquipmentStatusUpdateView.as_view(), name='directory_equipmentstatus_update'),
    path('directory/equipmentstatus/delete/<int:pk>/', views.EquipmentStatusDeleteView.as_view(), name='directory_equipmentstatus_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

employee/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from simple_history.models import HistoricalRecords
from phonenumber_field.modelfields import PhoneNumberField

from nguhub.models import Placement


class ActionPost(models.Model):
	name = models.CharField(max_length=30,
						verbose_name='Назва')
	notes = models.CharField(max_length=255,
						verbose_name = 'Додаткові відомості')

	class Meta:
		verbose_name = 'Бойовий пост'
		verbose_name_plural = 'Бойові пости'

	def get_update_url(self):
		return reverse('directory_actionpost_update', args=[self.id])

	def get_delete_url(self):
		return reverse('directory_actionpost_delete', args=[self.id])

	def __str__(self):
		return '{} ({})'.format(self.name, self.notes)


class Employee(models.Model):
	def directory_path(instance, filename):
		return 'media/employee/{0}/{1}'.format(instance.id, filename)


	RANK_CHOICES = (
        (u"сл.", u"Службовець"),
        (u"солд.", u"Солдат"),
        (u"ст.солд.", u"Старший солдат"),
        (u"мол.с-нт", u"Молодший сержант"),
        (u"с-нт", u"Сержант"),
        (u"ст.с-нт", u"Старший сержант"),
        (u"гол.с-нт", u"Головний сержант"),
        (u"шт.с-нт", u"Штаб-сержант"),
        (u"м.с-нт", u"Майстер-сержант"),
        (u"ст.м.с-нт", u"Старший майстер-сержант"),
        (u"гол.м.с-нт", u"Головний майстер-сержант"),
        (u"мол.л-нт", u"Молодший лейтенант"),
        (u"л-нт", u"Лейтенант"),
        (u"ст.л-нт", u"Старший лейтенант"),
        (u"к-н", u"Капітан"),
        (u"м-р", u"Майор"),
        (u"п/п-к", u"Підполковник"),
        (u"п-к", u"Полковник"),
        (u"бриг.ген.", u"Бригадний генерал"),
        (u"ген.м-р", u"Генерал-майор"),
        (u"ген.л-нт", u"Генерал-лейтенант"),
        (u"ген.", u"Генерал")
    )

	placement = models.ForeignKey(Placement,
							on_delete=models.PROTECT,
							verbose_name='Локація користувача')
	rank = models.CharField(max_length=30, 
							choices=RANK_CHOICES, 
							blank=False, 
							null=False, 
							verbose_name='Звання')
	firstname = models.CharField(max_length=15,
							blank=False, 
							null=False, 
							verbose_name="Ім'я")
	lastname = models.CharField(max_length=25,
							blank=False, 
							null=False, 
							verbose_name='Прізвище')
	surname = models.CharField(max_length=25,
							blank=True, 
							null=True, 
							verbose_name='По батькові')
	position = models.CharField(max_length=100,
							blank=False, 
							null=False, 
							verbose_name='посада')
	notes = models.CharField(max_length=1024,
							blank=True, 
							null=True, 
							verbose_name='Додатковий коментар')
	officialPhone = models.CharField(max_length=10, 
							blank=True, 
							null=True, 
							verbose_name='Службовий номер телефону')
	personalPhone = PhoneNumberField(blank=True, 
							null=True, 
							unique=True)
	photo = models.ImageField(upload_to=directory_path, 
							blank=True, 
							null=True,
							verbose_name='Фотографія')
	is_operator = models.BooleanField(
							null = True,
							default = True,
							verbose_name = u'Зв\'язківець')
	actionPost = models.ManyToManyField(ActionPost,
							verbose_name = 'Бойовий пост')
	history = HistoricalRecords()

	class Meta:
		verbose_name = 'Співробітник'
		verbose_name_plural = 'Співробітники'

	def get_absolute_url(self):
		return reverse('employee:detail',
			args=[self.id])

	def get_update_url(self):
		return reverse('employee:update',
			args=[self.id])

	def get_delete_url(self):
		return reverse('employee:delete',
			args=[self.id])

	def fullname(self):
		return '{} {}'.format(self.lastname, self.firstname)

	def shortname(self):
		if self.surname is None:
			surname = ''
		else :
			surname = self.surname[0]
		return '{} {}.{}.'.format(self.lastname, self.firstname[0],surname)

	def shortposition(self):
		pos = ''
		for i in self.position.split(" "):
			pos = pos + i[0]
		return pos.upper()

	def __str__(self):
		return '{} {}'.format(self.lastname, self.firstname)

employee/views.py
from django.conf import settings # import the settings file
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, QueryDict
from django.urls import reverse_lazy
from urllib.parse import urlencode
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from .models import Employee
from .forms import EmployeeCreateForm, EmployeeUpdateForm
from nguhub.models import Location, Placement


@login_required(login_url="/")
def employee_list(request):
    ADMIN_SITE_NAME = settings.DEFAULT_SITE_NAMING
    template = 'employee/list.html'
    employees = Employee.objects.all()
    placements = Placement.objects.all()
    sort_dict = (
        {'id':1, 'key':'rank','value':'Звання'},
        {'id':2, 'key':'lastname','value':'Прізвище'},
        {'id':3, 'key':'position','value':'Посада'},
        {'id':4, 'key':'placement__name','value':'Локація'},
        )

    # Отримати параметри запиту GET
    placement_filters = request.GET.getlist('placement[]')
    sort_field = request.GET.get('sort', 'lastname')
    sort_order = request.GET.get('order', 'asc')
    search_query = request.GET.get('q', '')
    
    # Фільтрувати дані за категорією
    if placement_filters:
        employees = employees.filter(placement__name__in=placement_filters)
    
    # Фільтрувати дані за пошуком
    if search_query:
        employees = employees.filter(
                    Q(firstname__icontains=search_query) |
                    Q(lastname__icontains=search_query) |
                    Q(position__icontains=search_query)
                    )

    # Сортувати дані за вибраним полем
    ordering = (sort_field, '-' + sort_field)[sort_order == 'desc']
    employees = employees.order_by(ordering)
    
    # Передати дані в шаблон
    context = {
        'ADMIN_SITE_NAME': ADMIN_SITE_NAME,
        'employees': employees,
        'placements': placements,
        'selected_placements':placement_filters,
        'sort_dict':sort_dict,
        'sort_field': sort_field,
        'sort_order': sort_order,
        'search_query': search_query
    }
    return render(request, template, context)


@login_required(login_url="/")
def employee_detail(request, pk):
    ADMIN_SITE_NAME = settings.DEFAULT_SITE_NAMING
    template = 'employee/detail.html'
    employee = get_object_or_404(Employee, id=pk,)
    #responsibleEquipment = Equipment.objects.filter(responsible=pk).order_by('category','name')
    #fixedEquipment = Equipment.objects.filter(fixed=pk).order_by('category','name')
    #employeeEquipment = Equipment.objects.filter(employee=pk).order_by('category','name')
    history = employee.history.all().order_by('history_date')

    context = {
        'ADMIN_SITE_NAME': ADMIN_SITE_NAME,
        'employee': employee,
        #'responsibleEquipment': responsibleEquipment,
        #'fixedEquipment': fixedEquipment,
        #'employeeEquipment': employeeEquipment,
        'history': history
    }
    return render(request,template, context)



class EmployeeCreateView(CreateView):
    model = Employee
    template_name = 'employee/add.html'
    form_class = EmployeeCreateForm

    def get_context_data(self, **kwargs):
        context = super(EmployeeCreateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        if self.request.POST.get('_save'):
            messages.success(self.request, 'Дані було успішно збережено.')
        if self.request.POST.get('_dismiss'):
            messages.success(self.request, 'Ви відмінили запит на створення')
        return super(EmployeeCreateView, self).form_valid(form)

    def get_success_url(self):
        if self.request.POST.get('_save'):
            return reverse_lazy('employee:list')
        if self.request.POST.get('_dismiss'):
            return reverse_lazy('employee:list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("signin")


class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = 'employee/update.html'
    form_class = EmployeeUpdateForm

    @property
    def has_permission(self):
        return self.user.is_active

    def get_context_data(self, **kwargs):
        context = super(EmployeeUpdateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        employee = self.get_object()
        if self.request.POST.get('_save'):
            messages.success(self.request, '\"{} {}\" було успішно змінено.'.format(employee.lastname, employee.firstname))
        if self.request.POST.get('_dismiss'):
            messages.success(self.request, 'Ви відмінили запит на зміну')
        return super(EmployeeUpdateView, self).form_valid(form)

    def get_success_url(self):
        if self.request.POST.get('_save'):
            return reverse_lazy('employee:list')
        if self.request.POST.get('_dismiss'):
            return reverse_lazy('employee:list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("signin")


class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'employee/confirm_delete.html'

    def get_success_url(self):
        if self.request.POST.get('_confirm'):
            messages.success(self.request, 'Користувача було успішно видалено.')
        if self.request.POST.get('_cancel'):
            messages.success(self.request, 'Ви відмінили запит на видалення')
        return reverse_lazy('employee:list')

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('_cancel'):
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(EmployeeDeleteView, self).post(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("signin")



'''  History   '''
@login_required(login_url="/")
def employee_history_list(request):
    ADMIN_SITE_NAME = settings.DEFAULT_SITE_NAMING
    template = 'employee/history_list.html'
    history = Employee.history.filter(history_type='-')
    context = {
        'history': history
    }
    return render(request, template, context)

templates/employee/confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete Equipment {% endblock title %}
{% block content %}
<div class="card shadow-lg o-hidden border-0 my-5">
	<div class="card-body p-0">
		<div class="row">
			<div class="col-lg-12">
				<div class="p-5">
					<div class="text-center">
						<h4 class="text-light mb-4">Видалити співробітника {{employee.fullname}}?</h4>
					</div>
					{% if message %}
						<div class="alert alert-success" role="alert">
							{% for message in messages %}
								{{ message }}
							{% endfor %}
						</div>
					{% endif %}
					<form method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-sm-3 mb-3 mb-sm-0">
							</div>
							<div class="col-sm-3 mb-3 mb-sm-0">
								<input class="default btn  btn-sm d-block btn-user w-100"  type="submit" value="Так, Видалити" name="_confirm">
							</div>
							<div class="col-sm-3 mb-3 mb-sm-0">
								<input class="default btn  btn-sm d-block btn-user w-100"  type="submit" value="Ні, Я помилився" name="_cancel">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/employee/history_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Обладнання{% endblock title %}
{% block content %}
  <div class="wrapper">
    <div class="main-panel">
      <div class="detailcontent">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card ">
              <div class="card-header">
                <h4 class="card-title">Історія видалення матеріальних цінностей</h4>
              </div>
              <div class="row">
                <div class="col-lg-10 col-md-10 col-sm-10">
                  <form method="GET" action="{% url 'employee:list' %}">
                    <input type="text" class="form-control search_field" name="q" placeholder="Пошук" value={{search_query}}>
                    <button class="btn btn-sm search_field" type="submit">Шукати</button>
                  </form>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-hover tablesorter dataTable no-footer table-striped" id="" cellspacing="0">
                    <thead class=" text-primary text-center">
                      <tr>
                        <th>Дата видалення </th>
                        <th>Хто видалив </th>
                        <th>Звання</th>
                        <th>П.І.Б.</th>
                        <th>Посада</th>
                        <th>Локація</th>
                        <th>Контакти</th>
                        <th>Коментар</th>
                      </tr>
                    </thead>
                    <tbody class="text-center">
                      {% for record in history %}
                      <tr>
                        <td> {{record.history_date|date:"d.m.Y H:i"}}</td>
                        <td> {{ record.history_user.first_name }} {{ record.history_user.last_name }}</td>
                        <td> {{ record.get_rank_display }} </td>
                        <td> {{ record.lastname }} {{ record.firstname }} {{ record.surname }} </td>
                        <td> {{ record.position }} </td>
                        <td>{{record.placement.name}}<br>
                          <span class="text-muted">{{record.placement.location.name}}</span><br>
                          <span class="text-muted">{{record.placement.location.address}}</span></td>
                        <td>
                          <span class="text-muted">{{record.officialPhone|default_if_none:""}}</span><br>
                          <span class="text-muted">{{record.personalPhone|default_if_none:""}}</span>
                        </td>
                        <td> {{record.comment|default_if_none:""}} </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <div class="copyright">
            © 2023 made with <i class="tim-icons icon-heart-2"></i> by <b>Ruslan Tokar</b> for a 3002 NGU.
          </div>
        </div>
      </footer>
    </div>
  </div>
{% endblock content %}
{% block extra_js %}
  <script>
    $(document).ready(function() {
      //Скрипт для процесингу фільтрів та сортування
      $('#equipmentFilterForm').submit(function(event) {
        event.preventDefault();
        $.ajax({
          url: $(this).attr('action'),
          data: $(this).serialize(),
          success: function(data) {
            $('.content').html(data);
          }
        });
      });
    });
    //Скрипт для відкриття модального вікна додавання обладнання
    $(document).on("click", "#add-equipment-btn", function() {
        console.log("Press")
        $('#add-equipment-modal').modal('show');
    });
    $(document).ready(function () {
      $('#dtHorizontalVerticalExample').DataTable({
        "scrollX": true,
        "scrollY": 200,
      });
      $('.dataTables_length').addClass('bs-select');
    });
  </script>
  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
    var input = document.querySelector('#search-form input[name="q"]');
    input.addEventListener('input', function() {
        input.closest('form').submit();
    });
});
  </script>
{% endblock extra_js %}

templates/employee/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Співробітники{% endblock title %}
{% block content %}
  <div class="wrapper">
    {% block sidebar %}
    <div class="sidebar" data="black">
      <div class="sidebar-wrapper">
        <div id="accordion">
          <div class="card sidebarcard">
            <form id="employeeFilterForm" method="get" action="{% url 'employee:list' %}">
              <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                  <button class="btn btn-link" 
                          type="button"
                          data-toggle="collapse" 
                          data-target="#categoriesCollapse"
                          aria-expanded="true" 
                          aria-controls="categoriesCollapse">Локації</button>
                </h5>
              </div>              
              <div id="categoriesCollapse" class="collapse show">
                <div class="form-group">
                  {% for category in categories %}
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" 
                              name="category[]" id="{{ category.name }}" 
                              value="{{ category.name }}" {% if category.name in selected_categories %}checked{% endif %}>
                      <label class="form-check-label" for="{{ category.name }}">{{ category.name }}</label>
                    </div>
                  {% endfor %}
                </div>
              </div>
              <label for="sort">Сортування:</label>
              <select id="sort" name="sort">
                {% for sort in sort_dict %}
                <option value="{{sort.key}}" {% if sort_field == sort.key %}selected{% endif %}>{{sort.value}}</option>
                {% endfor %}
              </select>
              <label for="order">Напрямок:</label>
              <select id="order" name="order">
                <option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>А-я</option>
                <option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>Я-а</option>
              </select>
              <div align ="center">
              <button type="submit" class="btn btn-sm">Фільтрувати</button>
              </div>
            </form>
          </div>
        </div>
        <div class="text-center">
          <a href="{% url 'employee:add' %}">
            <button id="add-employee-btn" type="button" class="btn btn-sm">Додати нового співробітника</button>
          </a>
        </div>
      </div>
    </div>
    {% endblock sidebar %}
    <div class="main-panel">
      <div class="content">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card ">
              <div class="card-header">
                <h4 class="card-title">Співробітники</h4>
              </div>
              <div class="row">
                <div class="col-lg-10 col-md-10 col-sm-10">
                  <form method="GET" action="{% url 'employee:list' %}">
                    <input type="text" class="form-control search_field" name="q" placeholder="Пошук" value={{search_query}}>
                    <button class="btn btn-sm search_field" type="submit">Шукати</button>
                  </form>
                </div>
                <div class="text-right col-lg-1 col-md-1 col-sm-1" >
                  <a href="{% url 'employee:history' %}">
                    <button id="history-employee-btn" 
                            type="button" 
                            class="btn btn-outline-success btn-circle btn-sm btn-circle" 
                            data-toggle="modal" 
                            data-target="#history-employee-modal">
                      <i class="fa fa-history"> Видалені записи</i>
                    </button>
                  </a>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive ">
                  <table class="table table-hover tablesorter " id="">
                    <thead class=" text-primary">
                      <tr>
                        <th> # </th>
                        <th>
                            Звання
                            {% if sort_field == 'rank' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th>
                            П.І.Б.
                            {% if sort_field == 'lastname' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th>
                            Посада
                            {% if sort_field == 'position' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th> 
                           Локація
                            {% if sort_field == 'category' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th> 
                           Контакти
                        </th>                        
                        <th> 
                           Коментар
                        </th>
                        <th> Управління </th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for employee in employees %}
                      <tr class="row-link">
                        <td> <a href="{{ employee.get_absolute_url }}">{{ forloop.counter }} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.get_rank_display}} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.fullname}} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.position}} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">
                            {{employee.category.name}}<br>
                            <span class="text-muted">{{employee.category.address}}</span>
                          </a>
                        <td> 
                          <a href="{{ employee.get_absolute_url }}">
                            <span class="text-muted">{{employee.officialPhone|default_if_none:""}}</span><br>
                            <span class="text-muted">{{employee.personalPhone|default_if_none:""}}</span>
                          </a>
                        </td>                        
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.coment}} </a></td>
                        <td> 
                          <a href="{{ employee.get_update_url }}">
                            <button id="update-employee-btn" 
                                    type="button" 
                                    class="btn btn-outline-success btn-circle btn-sm btn-circle" 
                                    data-toggle="modal" 
                                    data-target="#update-employee-modal">
                              <i class="fa fa-edit"></i>
                            </button>
                          </a>
                          <a href="{{ employee.get_delete_url }}">
                            <button id="delete-employee-btn" 
                                    type="button" 
                                    class="btn btn-outline-success btn-circle btn-sm btn-circle" 
                                    data-toggle="modal" 
                                    data-target="#delete-employee-modal">
                              <i class="fa fa-trash"></i>
                            </button>
                          </a>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <div class="copyright">
            © 2023 made with <i class="tim-icons icon-heart-2"></i> by <b>Ruslan Tokar</b> for a 3002 NGU.
          </div>
        </div>
      </footer>
    </div>
  </div>
{% endblock content %}
{% block extra_js %}
  <script>
    $(document).ready(function() {
      $('#employeeFilterForm').submit(function(event) {
        event.preventDefault();
        $.ajax({
          url: $(this).attr('action'),
          data: $(this).serialize(),
          success: function(data) {
            $('.content').html(data);
          }
        });
      });
    });
  </script>
{% endblock extra_js %}