employee/urls.py
from django.urls import path
from . import views


app_name = 'employee'
urlpatterns = [
    path('', views.employee_list, name='list'),
    path('<int:pk>/', views.employee_detail, name='detail'),
    path('add/', views.EmployeeCreateView.as_view(), name='add'),
    path('update/<int:pk>/', views.EmployeeUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.EmployeeDeleteView.as_view(), name='delete'),
    path('history/', views.employee_history_list, name='history'),
    
]

nguhub/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.user_login, name='signin'),
    path('logout/', views.user_logout, name='logout'),

    path('employee/', include('employee.urls', namespace='employee')),
    path('equipment/', include('equipment.urls', namespace='equipment')),

    # Довідники
     ##Location
    path('directory/location/', views.directory_location_list, name='directory_location_list'),
    path('directory/location/add/', views.LocationCreateView.as_view(), name='directory_location_add'),
    path('directory/location/update/<int:pk>/', views.LocationUpdateView.as_view(), name='directory_location_update'),
    path('directory/location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='directory_location_delete'),
     ##Placement
    path('directory/placement/', views.directory_placement_list, name='directory_placement_list'),
    path('directory/placement/add/', views.PlacementCreateView.as_view(), name='directory_placement_add'),
    path('directory/placement/update/<int:pk>/', views.PlacementUpdateView.as_view(), name='directory_placement_update'),
    path('directory/placement/delete/<int:pk>/', views.PlacementDeleteView.as_view(), name='directory_placement_delete'),
    ##ActionPost
    path('directory/actionpost/', views.directory_actionpost_list, name='directory_actionpost_list'),
    path('directory/actionpost/add/', views.ActionPostCreateView.as_view(), name='directory_actionpost_add'),
    path('directory/actionpost/update/<int:pk>/', views.ActionPostUpdateView.as_view(), name='directory_actionpost_update'),
    path('directory/actionpost/delete/<int:pk>/', views.ActionPostDeleteView.as_view(), name='directory_actionpost_delete'),
    ##EquipmentCategory
    path('directory/equipmentcategory/', views.directory_equipmentcategory_list, name='directory_equipmentcategory_list'),
    path('directory/equipmentcategory/add/', views.EquipmentCategoryCreateView.as_view(), name='directory_equipmentcategory_add'),
    path('directory/equipmentcategory/update/<int:pk>/', views.EquipmentCategoryUpdateView.as_view(), name='directory_equipmentcategory_update'),
    path('directory/equipmentcategory/delete/<int:pk>/', views.EquipmentCategoryDeleteView.as_view(), name='directory_equipmentcategory_delete'),
    ##EquipmentStatuses
    path('directory/equipmentstatus/', views.directory_equipmentstatus_list, name='directory_equipmentstatus_list'),
    path('directory/equipmentstatus/add/', views.EquipmentStatusCreateView.as_view(), name='directory_equipmentstatus_add'),
    path('directory/equipmentstatus/update/<int:pk>/', views.EquipmentStatusUpdateView.as_view(), name='directory_equipmentstatus_update'),
    path('directory/equipmentstatus/delete/<int:pk>/', views.EquipmentStatusDeleteView.as_view(), name='directory_equipmentstatus_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

employee/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from simple_history.models import HistoricalRecords
from phonenumber_field.modelfields import PhoneNumberField

from nguhub.models import Placement


class ActionPost(models.Model):
	name = models.CharField(max_length=30,
						verbose_name='Назва')
	notes = models.CharField(max_length=255,
						verbose_name = 'Додаткові відомості')

	class Meta:
		verbose_name = 'Бойовий пост'
		verbose_name_plural = 'Бойові пости'

	def get_update_url(self):
		return reverse('directory_actionpost_update', args=[self.id])

	def get_delete_url(self):
		return reverse('directory_actionpost_delete', args=[self.id])

	def __str__(self):
		return '{} ({})'.format(self.name, self.notes)


class Employee(models.Model):
	def directory_path(instance, filename):
		return 'media/employee/{0}/{1}'.format(instance.id, filename)


	RANK_CHOICES = (
        (u"сл.", u"Службовець"),
        (u"солд.", u"Солдат"),
        (u"ст.солд.", u"Старший солдат"),
        (u"мол.с-нт", u"Молодший сержант"),
        (u"с-нт", u"Сержант"),
        (u"ст.с-нт", u"Старший сержант"),
        (u"гол.с-нт", u"Головний сержант"),
        (u"шт.с-нт", u"Штаб-сержант"),
        (u"м.с-нт", u"Майстер-сержант"),
        (u"ст.м.с-нт", u"Старший майстер-сержант"),
        (u"гол.м.с-нт", u"Головний майстер-сержант"),
        (u"мол.л-нт", u"Молодший лейтенант"),
        (u"л-нт", u"Лейтенант"),
        (u"ст.л-нт", u"Старший лейтенант"),
        (u"к-н", u"Капітан"),
        (u"м-р", u"Майор"),
        (u"п/п-к", u"Підполковник"),
        (u"п-к", u"Полковник"),
        (u"бриг.ген.", u"Бригадний генерал"),
        (u"ген.м-р", u"Генерал-майор"),
        (u"ген.л-нт", u"Генерал-лейтенант"),
        (u"ген.", u"Генерал")
    )

	placement = models.ForeignKey(Placement,
							on_delete=models.PROTECT,
							verbose_name='Локація користувача')
	rank = models.CharField(max_length=30, 
							choices=RANK_CHOICES, 
							blank=False, 
							null=False, 
							verbose_name='Звання')
	firstname = models.CharField(max_length=15,
							blank=False, 
							null=False, 
							verbose_name="Ім'я")
	lastname = models.CharField(max_length=25,
							blank=False, 
							null=False, 
							verbose_name='Прізвище')
	surname = models.CharField(max_length=25,
							blank=True, 
							null=True, 
							verbose_name='По батькові')
	position = models.CharField(max_length=100,
							blank=False, 
							null=False, 
							verbose_name='посада')
	notes = models.CharField(max_length=1024,
							blank=True, 
							null=True, 
							verbose_name='Додатковий коментар')
	officialPhone = models.CharField(max_length=10, 
							blank=True, 
							null=True, 
							verbose_name='Службовий номер телефону')
	personalPhone = PhoneNumberField(blank=True, 
							null=True, 
							unique=True)
	photo = models.ImageField(upload_to=directory_path, 
							blank=True, 
							null=True,
							verbose_name='Фотографія')
	is_operator = models.BooleanField(
							null = True,
							default = True,
							verbose_name = u'Зв\'язківець')
	actionPost = models.ManyToManyField(ActionPost,
							verbose_name = 'Бойовий пост')
	history = HistoricalRecords()

	class Meta:
		verbose_name = 'Співробітник'
		verbose_name_plural = 'Співробітники'

	def get_absolute_url(self):
		return reverse('employee:detail',
			args=[self.id])

	def get_update_url(self):
		return reverse('employee:update',
			args=[self.id])

	def get_delete_url(self):
		return reverse('employee:delete',
			args=[self.id])

	def fullname(self):
		return '{} {}'.format(self.lastname, self.firstname)

	def shortname(self):
		if self.surname is None:
			surname = ''
		else :
			surname = self.surname[0]
		return '{} {}.{}.'.format(self.lastname, self.firstname[0],surname)

	def shortposition(self):
		pos = ''
		for i in self.position.split(" "):
			pos = pos + i[0]
		return pos.upper()

	def __str__(self):
		return '{} {}'.format(self.lastname, self.firstname)

templates/element_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Деталізація комплектуючого{% endblock title %}
{% block content %}
<div class="wrapper">
  <div class="main-panel">
    <div class="detailcontent">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="card ">
            <!--<h2 class="card-title">Деталізація обраного обладнання</h2>-->
            <div class="card-body">
              <h2>{{element.name}}</h2>
              <div class="equipment">
                <div class="equipment-image">
                  <img src="{{equipment.photo.url}}" alt="{{equipment.name}}">
                </div>
                <div class="equipment-info">
                  <p><span>Категорія</span>{{element.category.name}}</p>
                  <p><span>Серійний номер</span>{{element.serialNumber}}</p>
                  <p><span>Статус</span>{{element.status.name}}</p>
                  <p><span>Де встановлено</span>{{element.equipment.name}} S/N: {{element.equipment.serialNumber}}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <div class="copyright">
            © 2023 made with <i class="tim-icons icon-heart-2"></i> by <b>Ruslan Tokar</b> for a 3002 NGU.
          </div>
        </div>
      </footer>
    </div>
  </div>
</div>
{% endblock content %}
{% block extra_js %}
{% endblock extra_js %}

templates/element_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Комплектуючі{% endblock title %}
{% block content %}
  <div class="wrapper">
    {% block sidebar %}
    <div class="sidebar" data="black">
      <div class="sidebar-wrapper">
        <div id="accordion">
          <div class="card sidebarcard">
            <form id="elementFilterForm" method="get" action="{% url 'element:list' %}">
              <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                  <button class="btn btn-link" 
                          type="button"
                          data-toggle="collapse" 
                          data-target="#categoriesCollapse"
                          aria-expanded="true" 
                          aria-controls="categoriesCollapse">Категорії</button>
                </h5>
              </div>              
              <div id="categoriesCollapse" class="collapse show">
                <div class="form-group">
                  {% for category in categories %}
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" 
                              name="category[]" id="{{ category.name }}" 
                              value="{{ category.name }}" {% if category.name in selected_categories %}checked{% endif %}>
                      <label class="form-check-label" for="{{ category.name }}">{{ category.name }}</label>
                    </div>
                  {% endfor %}
                </div>
              </div>
              <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                  <button class="btn btn-link" 
                          type="button"
                          data-toggle="collapse" 
                          data-target="#statusCollapse"
                          aria-expanded="true" 
                          aria-controls="statusCollapse">Статус</button>
                </h5>
              </div>
              <div id="statusCollapse" class="collapse show">
                <div class="form-group">
                  {% for status in statuses %}
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" 
                              name="status[]" id="{{ status.name }}" 
                              value="{{ status.name }}" {% if status.name in selected_statuses %}checked{% endif %}>
                      <label class="form-check-label" for="{{ status.name }}">{{ status.name }}</label>
                    </div>
                  {% endfor %}
                </div>
              </div>
              <label for="sort">Сортування:</label>
              <select id="sort" name="sort">
                {% for sort in sort_dict %}
                <option value="{{sort.key}}" {% if sort_field == '{{sort.key}}' %}selected{% endif %}>{{sort.value}}</option>
                {% endfor %}
              </select>
              <label for="order">Напрямок:</label>
              <select id="order" name="order">
                <option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>А-я</option>
                <option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>Я-а</option>
              </select>
              <div align ="center">
              <button type="submit" class="btn">Фільтрувати</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock sidebar %}
    <div class="main-panel">
      <div class="content">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card ">
              <div class="card-header">
                <h4 class="card-title">Журнал списку комплектуючіх</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive ">
                  <table class="table table-hover tablesorter " id="">
                    <thead class=" text-primary">
                      <tr>
                        <th> # </th>
                        <th>
                            Назва
                            {% if sort_field == 'name' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th>
                            Об'єм
                        </th>
                        <th> 
                           Категорія
                            {% if sort_field == 'category' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th> 
                           Серійний номер
                        </th>
                        <th> 
                           Де встановлено
                            {% if sort_field == 'equipment' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th> 
                           Статус
                            {% if sort_field == 'status' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        {% if user.is_staff %}
                          <th> Управління </th>
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                      {% for element in elements %}
                      <tr class="row-link">
                        <td> <a href="{{ element.get_absolute_url }}">{{ forloop.counter }} </a></td>
                        <td> <a href="{{ element.get_absolute_url }}">{{element.name}} </a></td>
                        <td> <a href="{{ element.get_absolute_url }}">{{element.value}} </a></td>
                        <td> <a href="{{ element.get_absolute_url }}">{{element.category.name}} </a></td>
                        <td> <a href="{{ element.get_absolute_url }}">{{element.serialNumber}} </a></td>
                        <td> 
                          <a href="{{ element.get_absolute_url }}">
                            {% if element.equipment.name %}
                              <span>{{element.equipment.name}}</span><br>
                              <span>S/N: {{element.equipment.serialNumber}}</span><br>
                              <span class="text-muted">{{element.equipment.employee.get_rank_display}}</span><br>
                              <span class="text-muted">{{element.equipment.employee.fullname}}</span>
                            {% else %}
                              <span>Н/Д</span>
                            {% endif %}
                          </a>
                        </td>
                        <td> <a href="{{ element.get_absolute_url }}">{{element.status}} </a></td>
                        <td> <a href="{{ element.get_absolute_url }}"></a> </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <div class="copyright">
            © 2023 made with <i class="tim-icons icon-heart-2"></i> by <b>Ruslan Tokar</b> for a 3002 NGU.
          </div>
        </div>
      </footer>
    </div>
  </div>
{% endblock content %}
{% block extra_js %}
  <script>
    $(document).ready(function() {
      $('#elementFilterForm').submit(function(event) {
        event.preventDefault();
        $.ajax({
          url: $(this).attr('action'),
          data: $(this).serialize(),
          success: function(data) {
            $('.content').html(data);
          }
        });
      });
    });
  </script>
  <script src="{%static "js/script.js" %}"></script>
{% endblock extra_js %}

templates/employee_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Співробітники{% endblock title %}
{% block content %}
  <div class="wrapper">
    {% block sidebar %}
    <div class="sidebar" data="black">
      <div class="sidebar-wrapper">
        <div id="accordion">
          <div class="card sidebarcard">
            <form id="employeeFilterForm" method="get" action="{% url 'employee:list' %}">
              <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                  <button class="btn btn-link" 
                          type="button"
                          data-toggle="collapse" 
                          data-target="#categoriesCollapse"
                          aria-expanded="true" 
                          aria-controls="categoriesCollapse">Категорії</button>
                </h5>
              </div>              
              <div id="categoriesCollapse" class="collapse show">
                <div class="form-group">
                  {% for category in categories %}
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" 
                              name="category[]" id="{{ category.name }}" 
                              value="{{ category.name }}" {% if category.name in selected_categories %}checked{% endif %}>
                      <label class="form-check-label" for="{{ category.name }}">{{ category.name }}</label>
                    </div>
                  {% endfor %}
                </div>
              </div>
              <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                  <button class="btn btn-link" 
                          type="button"
                          data-toggle="collapse" 
                          data-target="#statusCollapse"
                          aria-expanded="true" 
                          aria-controls="statusCollapse">Статус</button>
                </h5>
              </div>
              <div id="statusCollapse" class="collapse show">
                <div class="form-group">
                  {% for status in statuses %}
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" 
                              name="status[]" id="{{ status.name }}" 
                              value="{{ status.name }}" {% if status.name in selected_statuses %}checked{% endif %}>
                      <label class="form-check-label" for="{{ status.name }}">{{ status.name }}</label>
                    </div>
                  {% endfor %}
                </div>
              </div>
              <label for="sort">Сортування:</label>
              <select id="sort" name="sort">
                {% for sort in sort_dict %}
                <option value="{{sort.key}}" {% if sort_field == '{{sort.key}}' %}selected{% endif %}>{{sort.value}}</option>
                {% endfor %}
              </select>
              <label for="order">Напрямок:</label>
              <select id="order" name="order">
                <option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>А-я</option>
                <option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>Я-а</option>
              </select>
              <div align ="center">
              <button type="submit" class="btn">Фільтрувати</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock sidebar %}
    <div class="main-panel">
      <div class="content">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card ">
              <div class="card-header">
                <h4 class="card-title">Співробітники</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive ">
                  <table class="table table-hover tablesorter " id="">
                    <thead class=" text-primary">
                      <tr>
                        <th> # </th>
                        <th>
                            Звання
                            {% if sort_field == 'rank' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th>
                            П.І.Б.
                            {% if sort_field == 'lastname' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th>
                            Посада
                            {% if sort_field == 'position' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th> 
                           Категорія
                            {% if sort_field == 'category' %}
                              {% if sort_order == 'asc' %}
                                &uarr;
                              {% else %}
                                &darr;
                              {% endif %}
                            {% endif %}
                        </th>
                        <th> 
                           Контакти
                        </th>                        
                        <th> 
                           Коментар
                        </th>
                        
                        {% if user.is_staff %}
                          <th> Управління </th>
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                      {% for employee in employees %}
                      <tr class="row-link">
                        <td> <a href="{{ employee.get_absolute_url }}">{{ forloop.counter }} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.get_rank_display}} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.fullname}} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.position}} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.category.name}} </a></td>
                        <td> 
                          <a href="{{ employee.get_absolute_url }}">
                            <span class="text-muted">{{employee.officialPhone}}</span><br>
                            <span class="text-muted">{{employee.personalPhone}}</span>
                          </a>
                        </td>                        
                        <td> <a href="{{ employee.get_absolute_url }}">{{employee.coment}} </a></td>
                        <td> <a href="{{ employee.get_absolute_url }}"></a> </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <div class="copyright">
            © 2023 made with <i class="tim-icons icon-heart-2"></i> by <b>Ruslan Tokar</b> for a 3002 NGU.
          </div>
        </div>
      </footer>
    </div>
  </div>
{% endblock content %}
{% block extra_js %}
  <script>
    $(document).ready(function() {
      $('#employeeFilterForm').submit(function(event) {
        event.preventDefault();
        $.ajax({
          url: $(this).attr('action'),
          data: $(this).serialize(),
          success: function(data) {
            $('.content').html(data);
          }
        });
      });
    });
  </script>
  <script src="{%static "js/script.js" %}"></script>
{% endblock extra_js %}